%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_1.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_3.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_4.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_5.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_6.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_7.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_8.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_9.py"

%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_1_cv.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_3_cv.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_4_cv.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_5_cv.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_6_cv.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_7_cv.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_8_cv.py"
%run "E:\krzys\informatyka-studia\sem-16-2017L\msi2\proj\SmogDetector\SmogDetector.Python\get_result_ver_9_cv.py"